import { PrismaClient, Region, DeadlineStatus } from "@prisma/client";
import { COUNTRY_COORDS } from "../lib/countries";

const prisma = new PrismaClient();

type Seed = {
  name: string;
  shortName?: string;
  organizer: string;
  country: string;
  countryCode: keyof typeof COUNTRY_COORDS;
  region: Region;
  latOverride?: number;
  lngOverride?: number;
  applyOpen?: string; // ISO date
  applyDeadline?: string; // ISO date
  deadlineStatus: DeadlineStatus;
  amount: string;
  currency?: string;
  fundingType: string;
  forWhom: string;
  requirements: string;
  description: string;
  details: string;
  officialUrl: string;
  tags: string[];
};

// UWAGA: Dane zebrane z oficjalnych źródeł (PARP, NCBR, EIC, gov.uk, sbir.gov itd.) w lipcu 2026.
// Programy z deadlineStatus = INDICATIVE mają terminy planowane wg opublikowanych harmonogramów
// i wymagają weryfikacji na dzień składania wniosku.

const programs: Seed[] = [
  // ============================ POLSKA ============================
  {
    name: "Startup Booster Poland (FENG)",
    shortName: "Startup Booster",
    organizer: "PARP / MFiPR",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2026-06-01",
    applyDeadline: "2026-10-31",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 400 000 PLN",
    currency: "PLN",
    fundingType: "grant bezzwrotny + akceleracja",
    forWhom: "startupy technologiczne poszukujące korporacyjnych partnerów wdrożeniowych",
    requirements:
      "startup zarejestrowany w PL, produkt/technologia na poziomie MVP+, gotowość do pilotażu z korporacją-partnerem",
    description:
      "Program akceleracyjny łączący startupy z korporacjami, oferuje bezzwrotne wsparcie na pilotaż wdrożenia.",
    details:
      "Nabór do 31 października 2026. Wsparcie obejmuje mentoring, granty do 400 tys. PLN oraz relacje inwestorsko-biznesowe.",
    officialUrl: "https://feng.parp.gov.pl/",
    tags: ["akceleracja", "korporacje", "MVP", "PL", "FENG"],
  },
  {
    name: "Platformy Startowe – Wschodni Akcelerator Biznesu 2 (FEPW)",
    shortName: "Platformy Startowe WAB2",
    organizer: "PARP / FEPW",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    latOverride: 51.2465,
    lngOverride: 22.5684, // Lublin (siedziba WAB)
    applyOpen: "2026-06-09",
    applyDeadline: "2027-05-10",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 600 000 PLN (po ukończeniu inkubacji)",
    currency: "PLN",
    fundingType: "inkubacja + grant bezzwrotny",
    forWhom:
      "startupy do 24 msc od rejestracji w województwach: lubelskie, podkarpackie, podlaskie, świętokrzyskie, warmińsko-mazurskie, mazowieckie (poza Warszawą)",
    requirements:
      "innowacyjny pomysł, siedziba w Polsce Wschodniej, gotowość do udziału w inkubacji (~9 msc), po zakończeniu składany wniosek na komponent IIa (dofinansowanie 600k)",
    description:
      "Ekosystem akceleracyjny dla Polski Wschodniej. Najpierw inkubacja, potem możliwość ubiegania się o 600 tys. PLN bezzwrotnego dofinansowania.",
    details:
      "Nabór 9.06.2026 – 10.05.2027. Prowadzące: Hub of Talents, Start in Podkarpackie, Connect, WAB2 i inne akceleratory.",
    officialUrl:
      "https://fepw.parp.gov.pl/component/grants/grants/platformy-startowe-dla-nowych-pomyslow-1",
    tags: ["Polska Wschodnia", "inkubacja", "MVP", "FEPW"],
  },
  {
    name: "Ścieżka SMART – MŚP (FENG)",
    shortName: "Ścieżka SMART MŚP",
    organizer: "PARP",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2026-09-15",
    applyDeadline: "2026-12-15",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "od kilkuset tys. do kilkudziesięciu mln PLN",
    currency: "PLN",
    fundingType: "grant bezzwrotny (moduły: B+R, wdrożenie, infrastruktura, kompetencje, cyfryzacja, zazielenienie, internacjonalizacja)",
    forWhom: "MŚP oraz konsorcja z jednostkami naukowymi",
    requirements:
      "moduł obowiązkowy: B+R lub Wdrożenie innowacji; dokumentacja techniczna i biznesowa; wpisanie w KIS",
    description:
      "Największy program dla MŚP w Polsce (FENG). Modułowy – wybierasz moduły odpowiadające etapowi Twojego projektu.",
    details:
      "Nabór wg planowanego harmonogramu FENG na 2026 – jesienna edycja. Terminy do potwierdzenia na parp.gov.pl przed składaniem.",
    officialUrl: "https://www.parp.gov.pl/harmonogram-naborow",
    tags: ["B+R", "wdrożenie", "FENG", "MŚP", "SMART"],
  },
  {
    name: "Ścieżka SMART – duże firmy (FENG, NCBR)",
    shortName: "Ścieżka SMART duże",
    organizer: "NCBR",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2026-10-01",
    applyDeadline: "2027-01-31",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "od kilku do kilkudziesięciu mln PLN",
    currency: "PLN",
    fundingType: "grant bezzwrotny (moduły B+R + wdrożenie)",
    forWhom: "duże przedsiębiorstwa oraz konsorcja",
    requirements: "moduł B+R obligatoryjny, wpisanie w KIS, TRL rosnący",
    description:
      "Ścieżka SMART dla dużych. Prowadzona przez NCBR. Kolejny nabór planowany na przełom 2026/2027.",
    details: "Ostateczne terminy publikuje NCBR (gov.pl/web/ncbr/harmonogram-konkursow-2026).",
    officialUrl: "https://www.gov.pl/web/ncbr/harmonogram-konkursow-2026",
    tags: ["B+R", "duże firmy", "FENG", "SMART", "NCBR"],
  },
  {
    name: "STEP – Biotech (FENG)",
    organizer: "PARP",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2026-11-15",
    applyDeadline: "2027-02-15",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "wg regulaminu naboru",
    currency: "PLN",
    fundingType: "grant bezzwrotny",
    forWhom: "MŚP w branżach biotechnologicznych (STEP – Strategic Technologies for Europe Platform)",
    requirements: "projekt w obszarze biotech, poziom TRL wg regulaminu, siedziba w PL",
    description:
      "Ścieżka STEP-Biotech – wsparcie kluczowych technologii strategicznych dla UE w Polsce.",
    details:
      "Po pierwszym naborze biotech planowanym na 2026, kolejny nabór wg harmonogramu FENG w Q4 2026 / Q1 2027.",
    officialUrl: "https://feng.parp.gov.pl/",
    tags: ["biotech", "STEP", "FENG"],
  },
  {
    name: "STEP – Digital & Deeptech (FENG)",
    organizer: "PARP",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2026-12-01",
    applyDeadline: "2027-03-15",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "wg regulaminu naboru",
    currency: "PLN",
    fundingType: "grant bezzwrotny",
    forWhom: "MŚP w branżach digital / deeptech / AI / chmura / półprzewodniki",
    requirements: "projekt w obszarze STEP (digital/deeptech), siedziba w PL, KIS",
    description:
      "Druga runda STEP-Digital/Deeptech planowana na przełom 2026/2027.",
    details: "Kwoty i szczegóły w regulaminie – opublikowane 30-45 dni przed naborem.",
    officialUrl: "https://feng.parp.gov.pl/",
    tags: ["AI", "deeptech", "STEP", "FENG"],
  },
  {
    name: "STEP – Cleantech (FENG)",
    organizer: "PARP",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyOpen: "2027-01-15",
    applyDeadline: "2027-04-15",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "wg regulaminu naboru",
    currency: "PLN",
    fundingType: "grant bezzwrotny",
    forWhom: "MŚP w branżach czystych technologii i efektywności zasobowej",
    requirements: "projekt w obszarze STEP-Cleantech, siedziba w PL",
    description: "Cleantech STEP – następny nabór planowany 2027 wg harmonogramu FENG.",
    details: "Weryfikuj termin bezpośrednio przed naborem – harmonogram jest aktualizowany kwartalnie.",
    officialUrl: "https://feng.parp.gov.pl/",
    tags: ["cleantech", "STEP", "FENG"],
  },
  {
    name: "Laboratorium Innowatora",
    organizer: "PARP / FENG",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    applyDeadline: "2027-06-30",
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "bezpłatny mentoring + wsparcie na etap pomysłu",
    currency: "PLN",
    fundingType: "wsparcie niefinansowe + drobne granty",
    forWhom: "osoby z pomysłami na innowacyjne produkty i usługi (przed założeniem firmy)",
    requirements: "innowacyjny pomysł, gotowość do udziału w programie mentoringowym",
    description:
      "Bezpłatny program dla pre-founderów: mentoring i rozwój koncepcji biznesowej.",
    details: "Ciągły nabór, nabory w rundach – szczegóły na PARP.",
    officialUrl: "https://www.parp.gov.pl/",
    tags: ["pre-seed", "mentoring", "pomysł"],
  },
  {
    name: "BGK – Fundusz Ekspansji Zagranicznej",
    organizer: "BGK",
    country: "Polska",
    countryCode: "PL",
    region: Region.PL,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 50 mln EUR (finansowanie kapitałowe / kredytowe, częściowo grantowe elementy pomocy)",
    currency: "EUR",
    fundingType: "wsparcie ekspansji (mix instrumentów; części pomocy publicznej bezzwrotne)",
    forWhom: "polskie firmy planujące ekspansję zagraniczną",
    requirements: "zdefiniowany plan ekspansji, spółka polska",
    description:
      "Wsparcie inwestycji zagranicznych polskich firm – dodatkowe komponenty grantowe wg regulaminu.",
    details: "Nabór ciągły – bezpośredni kontakt z BGK.",
    officialUrl: "https://www.bgk.pl/",
    tags: ["ekspansja", "BGK"],
  },

  // ============================ UE / EUROPA ============================
  {
    name: "EIC Accelerator – Open Call (cut-off 4 listopada 2026)",
    shortName: "EIC Accelerator 11/2026",
    organizer: "European Innovation Council",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyOpen: "2026-09-05",
    applyDeadline: "2026-11-04",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "grant do 2,5 mln EUR + inwestycja kapitałowa do 10 mln EUR (blended)",
    currency: "EUR",
    fundingType: "grant + equity (blended finance) lub grant-only",
    forWhom: "SME (w tym startupy) z krajów UE oraz krajów stowarzyszonych z Horyzontem Europa",
    requirements:
      "Step 1 GO (Short Proposal – składany ciągle), przełomowa innowacja z potencjałem skalowania na rynek globalny, TRL 5-9",
    description:
      "Flagowy program UE dla deeptech/SME. Sześć cut-offów w 2026: 7 sty, 4 mar, 6 maj, 8 lip, 2 wrz, 4 lis.",
    details:
      "Budżet 2026: 634 mln EUR (414 mln Open, 220 mln Challenges). Cut-off listopad = 4.11.2026.",
    officialUrl: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    tags: ["deeptech", "SME", "blended", "EIC"],
  },
  {
    name: "EIC Accelerator – cut-off 6 maja 2027 (harmonogram indykatywny)",
    organizer: "European Innovation Council",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2027-05-06",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "grant do 2,5 mln EUR + equity do 10 mln EUR",
    currency: "EUR",
    fundingType: "grant + equity",
    forWhom: "SME z UE i krajów stowarzyszonych",
    requirements: "Step 1 GO, TRL 5-9",
    description:
      "Kolejny cut-off planowany na maj 2027 – terminy programu pracy EIC 2027 publikowane w Q1 2027.",
    details: "Zawsze weryfikuj cut-off na eic.ec.europa.eu przed składaniem.",
    officialUrl: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    tags: ["deeptech", "EIC", "2027"],
  },
  {
    name: "EIC Pathfinder Open 2026",
    organizer: "European Innovation Council",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2026-05-12", // już minął w tym oknie, ale kolejna edycja Pathfinder Challenge:
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 3 mln EUR (grant)",
    currency: "EUR",
    fundingType: "grant bezzwrotny",
    forWhom: "konsorcja badawcze na wczesnym TRL 1-4",
    requirements: "konsorcjum min. 3 podmioty z 3 różnych państw członkowskich / stowarzyszonych",
    description:
      "Badania wczesnoetapowe wysokiego ryzyka. Open call rozstrzygnięto w maju 2026.",
    details:
      "Następny relewantny nabór: EIC Pathfinder Challenge – deadline 28 października 2026 (CONFIRMED).",
    officialUrl: "https://eic.ec.europa.eu/",
    tags: ["Pathfinder", "TRL 1-4", "konsorcjum"],
  },
  {
    name: "EIC Pathfinder Challenge 2026",
    organizer: "European Innovation Council",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2026-10-28",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 4 mln EUR (grant)",
    currency: "EUR",
    fundingType: "grant bezzwrotny",
    forWhom: "konsorcja lub pojedyncze podmioty w wybranych challenge",
    requirements: "wpisanie w jeden z ogłoszonych challenge, TRL 1-4",
    description: "Wyzwania tematyczne EIC – finansowanie ambitnych badań w kierunkowych obszarach.",
    details: "Deadline: 28 października 2026 17:00 CET.",
    officialUrl: "https://eic.ec.europa.eu/",
    tags: ["Pathfinder", "Challenge", "EIC"],
  },
  {
    name: "Eurostars Call 11 (deadline 10.09.2026)",
    organizer: "Eureka Network",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyOpen: "2026-07-09",
    applyDeadline: "2026-09-10",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "grant przyznawany krajowo (np. 500 000 EUR w NL); śr. budżet projektu ~1,5 mln EUR",
    currency: "EUR",
    fundingType: "grant bezzwrotny (finansowanie z krajowych agencji)",
    forWhom: "innowacyjne MŚP prowadzące projekt R&D w międzynarodowym konsorcjum",
    requirements:
      "konsorcjum min. 2 podmioty z 2 krajów Eureka, lider = MŚP, projekt do 36 msc, TRL 4-8, komercjalizacja w 24 msc po zakończeniu",
    description: "Największy międzynarodowy program R&D dla MŚP.",
    details: "Deadline 10 września 2026 14:00 CET.",
    officialUrl: "https://www.eurekanetwork.org/programmes-and-calls/eurostars/",
    tags: ["Eurostars", "R&D", "SME", "konsorcjum"],
  },
  {
    name: "Eurostars Call 12 (marzec 2027 – indykatywny)",
    organizer: "Eureka Network",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2027-03-18",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "wg krajowych limitów finansujących agencji",
    currency: "EUR",
    fundingType: "grant bezzwrotny (krajowo)",
    forWhom: "innowacyjne MŚP w konsorcjach",
    requirements: "konsorcjum międzynarodowe, lider = MŚP",
    description: "Kolejna, wiosenna edycja Eurostars.",
    details: "Harmonogram: dwa cut-offy rocznie (marzec + wrzesień).",
    officialUrl: "https://www.eurekanetwork.org/programmes-and-calls/eurostars/",
    tags: ["Eurostars", "R&D"],
  },
  {
    name: "Digital Europe Programme – jesienne nabory 2026",
    shortName: "DIGITAL 2026",
    organizer: "European Commission (HaDEA)",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyOpen: "2026-04-21",
    applyDeadline: "2026-10-01",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "wg konkretnego call (od kilkuset tys. do kilkudziesięciu mln EUR)",
    currency: "EUR",
    fundingType: "grant bezzwrotny (do 50-100% zależnie od action)",
    forWhom: "SME, konsorcja, administracja, dostawcy technologii",
    requirements: "wg konkretnego topicu (AI, chmura, cyber, umiejętności cyfrowe)",
    description:
      "Wdrożenia AI, chmury, cyberbezpieczeństwa i umiejętności cyfrowych w UE.",
    details:
      "Duży pakiet naborów otwiera się 21.04.2026, deadline 1.10.2026 17:00 CET. M.in. EdTech accelerator dla startupów.",
    officialUrl:
      "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/programmes/digital",
    tags: ["AI", "cyber", "digital", "SME"],
  },
  {
    name: "EIT Digital Venture Program 2027",
    organizer: "EIT Digital",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2027-02-28",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "granty + wsparcie akceleracyjne do ~300 000 EUR",
    currency: "EUR",
    fundingType: "grant + akceleracja",
    forWhom: "startupy deeptech z UE (deep-tech venture)",
    requirements: "produkt gotowy do skalowania, gotowość do internacjonalizacji",
    description: "Wsparcie EIT Digital dla europejskich startupów deeptech gotowych do skalowania.",
    details: "Kolejne rundy publikowane na eit.europa.eu/eit-community/eit-digital.",
    officialUrl: "https://www.eitdigital.eu/",
    tags: ["EIT", "deeptech", "akceleracja"],
  },
  {
    name: "EIT Health InnoStars Awards 2026",
    organizer: "EIT Health",
    country: "Unia Europejska",
    countryCode: "EU",
    region: Region.EU,
    applyDeadline: "2026-09-30",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "do 25 000 EUR + program akceleracyjny",
    currency: "EUR",
    fundingType: "grant + akceleracja",
    forWhom: "startupy healthtech z regionu InnoStars (m.in. Polska)",
    requirements: "startup healthtech / medtech / digital health, siedziba w kraju InnoStars",
    description: "Konkurs EIT Health dla startupów z Europy Środkowej i Południowej.",
    details: "Ogłoszenia rocznie; weryfikuj eithealth.eu.",
    officialUrl: "https://eithealth.eu/",
    tags: ["healthtech", "medtech", "EIT"],
  },
  {
    name: "EXIST Gründerstipendium (deadline 3.08.2026)",
    shortName: "EXIST",
    organizer: "BMWK (Bundesministerium für Wirtschaft und Klimaschutz)",
    country: "Niemcy",
    countryCode: "DE",
    region: Region.EU,
    applyDeadline: "2026-08-03",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount:
      "stypendium 1000-3000 EUR/os/msc x 12 msc + do 30 000 EUR na koszty rzeczowe (zespół)",
    currency: "EUR",
    fundingType: "stypendium bezzwrotne (100% pokrycia)",
    forWhom:
      "studenci, absolwenci i naukowcy z niemieckich uczelni / instytutów – projekty tech / knowledge-based",
    requirements:
      "afiliacja z uczelnią/instytutem w Niemczech; innowacyjny pomysł; wsparcie mentora akademickiego",
    description:
      "Bezzwrotne stypendium na 12 msc dla naukowców/absolwentów zakładających startup w Niemczech.",
    details:
      "Deadline: 3 sierpnia 2026 12:00. Ostatnia konsultacja: 29 lipca 2026.",
    officialUrl: "https://www.exist.de/",
    tags: ["stypendium", "uczelnie", "R&D", "DE"],
  },
  {
    name: "EXIST Gründerstipendium (deadline luty 2027 – indykatywny)",
    organizer: "BMWK",
    country: "Niemcy",
    countryCode: "DE",
    region: Region.EU,
    applyDeadline: "2027-02-01",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "jak wyżej",
    currency: "EUR",
    fundingType: "stypendium bezzwrotne",
    forWhom: "jak wyżej",
    requirements: "jak wyżej",
    description: "Kolejny cut-off EXIST – zwykle 2 rundy rocznie.",
    details: "Weryfikuj dokładny termin na exist.de.",
    officialUrl: "https://www.exist.de/",
    tags: ["stypendium", "DE"],
  },
  {
    name: "Bourse French Tech (Bpifrance)",
    organizer: "Bpifrance",
    country: "Francja",
    countryCode: "FR",
    region: Region.EU,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 50 000 EUR (do 70% wydatków kwalifikowalnych)",
    currency: "EUR",
    fundingType: "grant bezzwrotny",
    forWhom: "innowacyjne startupy z Francji <1 rok",
    requirements: "innowacyjny projekt tech, siedziba we Francji, plan biznesowy",
    description: "Grant Bpifrance dla wczesnych francuskich startupów innowacyjnych.",
    details: "Nabór ciągły – aplikacja przez bpifrance.fr.",
    officialUrl: "https://www.bpifrance.fr/catalogue-offres/bourse-french-tech",
    tags: ["seed", "innowacje", "FR"],
  },
  {
    name: "Bourse French Tech Émergence (deeptech)",
    organizer: "Bpifrance",
    country: "Francja",
    countryCode: "FR",
    region: Region.EU,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 90 000 EUR",
    currency: "EUR",
    fundingType: "grant bezzwrotny",
    forWhom: "deeptech startupy < 1 rok",
    requirements: "projekt deeptech (breakthrough technology), Francja",
    description: "Ścieżka dla deeptech w ramach Bpifrance – zwiększone finansowanie na etap emergence.",
    details: "Nabór ciągły; typowo 12 msc trwania projektu (do 18).",
    officialUrl: "https://www.bpifrance.fr/catalogue-offres/bourse-french-tech-emergence",
    tags: ["deeptech", "seed", "FR"],
  },
  {
    name: "Enterprise Ireland – Pre-Seed Start Fund",
    organizer: "Enterprise Ireland",
    country: "Irlandia",
    countryCode: "IE",
    region: Region.EU,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 100 000 EUR",
    currency: "EUR",
    fundingType: "convertible / equity + granty (część niedystrybuowalna)",
    forWhom:
      "HPSU (High Potential Start-Ups) z Irlandii – firmy tech na etapie pre-seed",
    requirements: "spółka irlandzka, potencjał zatrudnienia 10+ i eksportu 1M EUR w 3 lata",
    description: "Wsparcie Enterprise Ireland na start firmy z potencjałem eksportowym.",
    details: "Nabór ciągły przez Enterprise Ireland.",
    officialUrl: "https://www.enterprise-ireland.com/",
    tags: ["HPSU", "pre-seed", "IE"],
  },
  {
    name: "Vinnova – Innovative Startups (Sweden)",
    organizer: "Vinnova",
    country: "Szwecja",
    countryCode: "SE",
    region: Region.EU,
    applyOpen: "2026-09-01",
    applyDeadline: "2026-10-13",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "do 300 000 SEK (~26 000 EUR) w fazie 1; do 900 000 SEK w fazie 2",
    currency: "SEK",
    fundingType: "grant bezzwrotny",
    forWhom: "szwedzkie startupy < 5 lat, mniej niż 20 pracowników",
    requirements: "innowacyjny produkt/technologia, siedziba w Szwecji",
    description: "Popularny szwedzki grant startowy – dwie fazy.",
    details: "Nabory zwykle 2-3 razy w roku. Weryfikuj vinnova.se.",
    officialUrl: "https://www.vinnova.se/en/",
    tags: ["seed", "innowacje", "SE"],
  },
  {
    name: "Startup Estonia / EAS – R&D Grant",
    organizer: "EAS (Enterprise Estonia)",
    country: "Estonia",
    countryCode: "EE",
    region: Region.EU,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 500 000 EUR (do 45% kosztów)",
    currency: "EUR",
    fundingType: "grant bezzwrotny",
    forWhom: "estońskie firmy prowadzące R&D",
    requirements: "spółka estońska, projekt R&D",
    description: "Wsparcie R&D dla estońskich firm od EAS.",
    details: "Ciągły nabór, kwoty zależnie od komponentu.",
    officialUrl: "https://eas.ee/en/",
    tags: ["R&D", "EE"],
  },
  {
    name: "Innovate UK – Quantum Computing Applications 2026",
    organizer: "Innovate UK / UKRI",
    country: "Wielka Brytania",
    countryCode: "GB",
    region: Region.EU,
    applyDeadline: "2026-09-18",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 33 mln GBP (całkowity budżet konkursu)",
    currency: "GBP",
    fundingType: "grant bezzwrotny (do 70% dla MŚP)",
    forWhom: "MŚP i konsorcja z UK, obszar zastosowań komputerów kwantowych",
    requirements: "firma zarejestrowana w UK, projekt prowadzony w UK",
    description: "Konkurs Innovate UK w obszarze quantum applications.",
    details: "Deadline: 18 września 2026, 11:00 UK time.",
    officialUrl: "https://apply-for-innovation-funding.service.gov.uk/competition/search",
    tags: ["quantum", "R&D", "UK"],
  },
  {
    name: "Innovate UK – Pre-Commercialisation 2026",
    organizer: "Innovate UK / UKRI",
    country: "Wielka Brytania",
    countryCode: "GB",
    region: Region.EU,
    applyDeadline: "2026-07-08",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "do 25 mln GBP (budżet konkursu)",
    currency: "GBP",
    fundingType: "grant bezzwrotny",
    forWhom: "MŚP z UK w obszarach pre-komercjalizacji",
    requirements: "firma zarejestrowana w UK, projekt w UK",
    description: "Wsparcie na projekty pre-komercjalizacyjne w UK.",
    details: "Deadline: 8 lipca 2026.",
    officialUrl: "https://apply-for-innovation-funding.service.gov.uk/competition/search",
    tags: ["pre-commercial", "R&D", "UK"],
  },
  {
    name: "Innovate UK – Smart Grants (relaunch pilot)",
    organizer: "Innovate UK / UKRI",
    country: "Wielka Brytania",
    countryCode: "GB",
    region: Region.EU,
    applyDeadline: "2026-12-15",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "typowo od 100k do 2 mln GBP",
    currency: "GBP",
    fundingType: "grant bezzwrotny (do 70% MŚP)",
    forWhom: "startupy i MŚP prowadzące R&D w UK",
    requirements: "firma UK, innowacyjny projekt R&D dowolnej branży",
    description:
      "Smart Grants – flagowy program Innovate UK, po pauzie w 2025 wraca w formie pilotażu.",
    details:
      "Publikacja terminów na innovation funding service; obserwuj gov.uk – kolejne rundy 2026/2027.",
    officialUrl: "https://apply-for-innovation-funding.service.gov.uk/competition/search",
    tags: ["Smart Grants", "R&D", "UK"],
  },

  // ============================ ŚWIAT ============================
  {
    name: "NIH SBIR/STTR – Omnibus deadline wrzesień 2026",
    organizer: "National Institutes of Health",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    applyDeadline: "2026-09-05",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "Phase I do ~306 000 USD; Phase II do ~2 mln USD (2026)",
    currency: "USD",
    fundingType: "grant bezzwrotny (Phase I/II) – nie ma equity",
    forWhom: "US small business (<500 pracowników, US-owned) w obszarze biomed/health",
    requirements:
      "spółka zarejestrowana w USA, >50% własność US, PI zatrudniony >50% w firmie (SBIR)",
    description: "Stały cykl NIH: standardowe terminy 5.09, 5.01, 5.04.",
    details: "Deadline 5 września 2026. Kolejne: 5.01.2027 i 5.04.2027.",
    officialUrl: "https://seed.nih.gov/small-business-funding/find-funding/sbir-sttr-funding-opportunities",
    tags: ["SBIR", "biomed", "USA", "NIH"],
  },
  {
    name: "NIH SBIR/STTR – Omnibus deadline styczeń 2027",
    organizer: "NIH",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    applyDeadline: "2027-01-05",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "j.w.",
    currency: "USD",
    fundingType: "grant bezzwrotny",
    forWhom: "j.w.",
    requirements: "j.w.",
    description: "Kolejny standardowy cut-off NIH SBIR/STTR.",
    details: "Deadline 5 stycznia 2027 (dni robocze).",
    officialUrl: "https://seed.nih.gov/small-business-funding/find-funding/sbir-sttr-funding-opportunities",
    tags: ["SBIR", "NIH"],
  },
  {
    name: "NIH SBIR/STTR – Omnibus deadline kwiecień 2027",
    organizer: "NIH",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    applyDeadline: "2027-04-05",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "j.w.",
    currency: "USD",
    fundingType: "grant bezzwrotny",
    forWhom: "j.w.",
    requirements: "j.w.",
    description: "Kolejny standardowy cut-off NIH SBIR/STTR.",
    details: "Deadline 5 kwietnia 2027.",
    officialUrl: "https://seed.nih.gov/small-business-funding/find-funding/sbir-sttr-funding-opportunities",
    tags: ["SBIR", "NIH"],
  },
  {
    name: "NSF SBIR/STTR Project Pitch (rolling FY2027)",
    organizer: "National Science Foundation",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    latOverride: 38.8807,
    lngOverride: -77.1109,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "Phase I do 305 000 USD; Phase II do 2 mln USD (+ Phase IIB do 500k)",
    currency: "USD",
    fundingType: "grant bezzwrotny",
    forWhom: "US small business z deeptech / hard-tech (poza biomedycyną NIH)",
    requirements: "US small business, technologia deeptech z komercyjnym potencjałem",
    description: "Wpierw wysyłasz Project Pitch (3 strony), po zaproszeniu składasz Phase I.",
    details:
      "Nowe solicitations rusza 2 czerwca 2026; nowe pitche przyjmowane w rundach FY2027.",
    officialUrl: "https://seedfund.nsf.gov/solicitations/",
    tags: ["SBIR", "deeptech", "NSF"],
  },
  {
    name: "NASA SBIR/STTR – Phase I FY2026 Appendices",
    organizer: "NASA",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    applyOpen: "2026-04-21",
    applyDeadline: "2026-09-10",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "Phase I do 175 000 USD; Phase II do 1 mln USD",
    currency: "USD",
    fundingType: "grant bezzwrotny (kontrakt)",
    forWhom: "US small business w obszarach zainteresowań NASA",
    requirements: "topic z BAA NASA, small business zgodnie z definicją SBA",
    description: "Nowa struktura BAA – wiele appendices w ciągu roku.",
    details:
      "BAA ważne do 30 września 2027; pierwsze appendices deadline wrzesień 2026, kolejne w Q1/Q2 2027.",
    officialUrl: "https://www.nasa.gov/sbir_sttr/nasa-sbir-sttr-program-program-year-2026-information-hub/",
    tags: ["SBIR", "space", "NASA"],
  },
  {
    name: "DoD SBIR – FY2026 BAA (multiple releases)",
    organizer: "US Department of Defense",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    latOverride: 38.8719,
    lngOverride: -77.0563,
    applyDeadline: "2026-10-15",
    deadlineStatus: DeadlineStatus.CONFIRMED,
    amount: "Phase I do 250 000 USD; Phase II do 2 mln USD",
    currency: "USD",
    fundingType: "grant/kontrakt bezzwrotny",
    forWhom: "US small business w obszarach obronności (dual-use technologies)",
    requirements: "US small business, temat z BAA komponentu (Army/Navy/AF itd.)",
    description: "Nakładające się solicitations 2025.4 + FY2026 BAA po reautoryzacji programu.",
    details: "Wiele deadlin'ów czerwiec-październik 2026 zależnie od komponentu.",
    officialUrl: "https://www.dodsbirsttr.mil/",
    tags: ["SBIR", "defense", "DoD"],
  },
  {
    name: "USDA NIFA SBIR – Phase I 2026",
    organizer: "USDA NIFA",
    country: "USA",
    countryCode: "US",
    region: Region.WORLD,
    applyDeadline: "2026-10-08",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "Phase I do 175 000 USD; Phase II do 650 000 USD",
    currency: "USD",
    fundingType: "grant bezzwrotny",
    forWhom: "US small business w agrotech / bio-based / rural innovation",
    requirements: "US small business, temat wg USDA topics",
    description: "USDA SBIR – agri/food/rural tech.",
    details: "Termin roczny publikowany na nifa.usda.gov (typowo październik).",
    officialUrl: "https://www.nifa.usda.gov/grants/programs/sbir-sttr",
    tags: ["SBIR", "agritech", "USDA"],
  },
  {
    name: "Ideation Tnufa (Israel Innovation Authority)",
    shortName: "Tnufa",
    organizer: "Israel Innovation Authority",
    country: "Izrael",
    countryCode: "IL",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 200 000 ILS (~55 000 USD) – 80% budżetu, na 12 msc",
    currency: "ILS",
    fundingType: "grant warunkowo bezzwrotny (conditional grant)",
    forWhom:
      "izraelscy przedsiębiorcy i wczesne startupy (nawet przed założeniem spółki)",
    requirements: "obywatel/rezydent Izraela lub izraelska spółka, projekt tech na etapie idea/POC",
    description:
      "Etap seed IIA – validacja pomysłu, prototyp, ochrona IP.",
    details: "Nabór ciągły; osobne wyzwania tematyczne np. Critical Minerals (deadline 25.06.2026).",
    officialUrl: "https://innovationisrael.org.il/en/programs/ideation-tnufa-incentive-program/",
    tags: ["seed", "IIA", "Izrael"],
  },
  {
    name: "Startup SG Founder Grant",
    organizer: "Enterprise Singapore",
    country: "Singapur",
    countryCode: "SG",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 50 000 SGD + wsparcie mentora (AMP)",
    currency: "SGD",
    fundingType: "matching grant bezzwrotny (1:5, wkład własny 10k SGD)",
    forWhom:
      "first-time founder Singapur; ≥51% udziałów lokalnych; nowa spółka",
    requirements: "endorsement Accredited Mentor Partner (AMP), plan biznesowy, wkład 10k SGD",
    description: "Singapurski flagowy grant startowy dla first-time founderów.",
    details:
      "Aplikacja przez AMP (nie Business Grants Portal). Endorsement AMP 2-4 tyg.",
    officialUrl: "https://www.startupsg.gov.sg/programmes/4894/startup-sg-founder",
    tags: ["seed", "first-time founder", "SG"],
  },
  {
    name: "Enterprise Development Grant (EDG)",
    organizer: "Enterprise Singapore",
    country: "Singapur",
    countryCode: "SG",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 70% kosztów kwalifikowalnych (rzadko 80%)",
    currency: "SGD",
    fundingType: "grant bezzwrotny (co-funding)",
    forWhom: "spółki singapurskie (min. 30% lokalnych udziałów) na etapie skalowania",
    requirements:
      "spółka SG, finansowa zdolność do prowadzenia projektu, projekt w jednym z 3 filarów (core capabilities / innovation / market access)",
    description:
      "Grant Enterprise Singapore na rozwój i internacjonalizację singapurskich firm.",
    details: "Nabór ciągły przez Business Grants Portal (BGP).",
    officialUrl: "https://www.enterprisesg.gov.sg/financial-support/enterprise-development-grant",
    tags: ["scale-up", "SG"],
  },
  {
    name: "NRC IRAP (National Research Council Canada) – Core Stream",
    organizer: "NRC / Canada Innovation Corporation",
    country: "Kanada",
    countryCode: "CA",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "typowo 75-200k CAD dla nowych; do 10 mln CAD (rzadziej)",
    currency: "CAD",
    fundingType: "grant bezzwrotny (contribution)",
    forWhom: "kanadyjskie MŚP <500 pracowników prowadzące R&D",
    requirements: "spółka kanadyjska for-profit, projekt R&D, zdolność do komercjalizacji",
    description: "Sztandarowy kanadyjski program niedylucyjny (non-dilutive).",
    details:
      "Start = telefon 1-877-994-4727. Timeline: 3-4 msc do umowy, 4-6 msc do pierwszej płatności. W 2026-27 IRAP integruje się w Canada Innovation Corporation (CIC).",
    officialUrl: "https://nrc.canada.ca/en/support-technology-innovation",
    tags: ["R&D", "non-dilutive", "CA"],
  },
  {
    name: "Australia – Industry Growth Program (Early-Stage Commercialisation)",
    organizer: "Department of Industry, Science and Resources (AU)",
    country: "Australia",
    countryCode: "AU",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "50 000 – 250 000 AUD (Early-Stage); do 5 mln AUD (Growth)",
    currency: "AUD",
    fundingType: "matching grant bezzwrotny",
    forWhom: "australijskie SMEs / startupy w priorytetowych sektorach (Future Made in Australia)",
    requirements: "spółka AU, produkt/proces nowatorski, gotowość do komercjalizacji",
    description: "Główny program komercjalizacyjny rządu Australii (następca Accelerating Commercialisation).",
    details: "Nabór ciągły; oceny w rundach.",
    officialUrl: "https://business.gov.au/grants-and-programs/industry-growth-program",
    tags: ["commercialisation", "AU"],
  },
  {
    name: "Queensland Ignite Ideas Fund",
    organizer: "Advance Queensland",
    country: "Australia",
    countryCode: "AU",
    latOverride: -27.4698,
    lngOverride: 153.0251,
    region: Region.WORLD,
    applyDeadline: "2026-09-30",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "do 100 000 AUD (Ignite) lub do 200 000 AUD (Ignite Plus)",
    currency: "AUD",
    fundingType: "grant bezzwrotny",
    forWhom: "spółki z Queensland komercjalizujące nowe produkty/usługi",
    requirements: "siedziba w Queensland, projekt komercjalizacyjny",
    description: "Popularny program stanowy Queensland.",
    details: "Typowo 2-3 rundy w roku (Q2/Q3).",
    officialUrl: "https://advance.qld.gov.au/",
    tags: ["Queensland", "commercialisation", "AU"],
  },
  {
    name: "UAE – Mohammed bin Rashid Innovation Fund (MBRIF)",
    organizer: "Ministry of Finance UAE / Emirates Development Bank",
    country: "ZEA",
    countryCode: "AE",
    region: Region.WORLD,
    latOverride: 25.2048,
    lngOverride: 55.2708,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "gwarancje kredytowe + akceleracja; komponenty grantowe wg wyzwań",
    currency: "AED",
    fundingType: "gwarancje + akceleracja (część komponentów grantowa)",
    forWhom: "innowacyjne startupy z UAE lub globalne przenoszące się do UAE",
    requirements: "innowacyjność, gotowość do relokacji operacyjnej",
    description: "Program wspiera innowacyjne firmy w UAE poprzez gwarancje i akcelerator.",
    details: "Aplikacja ciągła; wybrane 'challenges' z bezzwrotnym elementem.",
    officialUrl: "https://www.mbrif.ae/",
    tags: ["UAE", "innovation"],
  },
  {
    name: "NEDO – Japan Startup Support (SBIR-J)",
    organizer: "NEDO / METI",
    country: "Japonia",
    countryCode: "JP",
    region: Region.WORLD,
    applyDeadline: "2026-11-30",
    deadlineStatus: DeadlineStatus.INDICATIVE,
    amount: "od kilku milionów JPY do kilkuset mln JPY",
    currency: "JPY",
    fundingType: "grant bezzwrotny",
    forWhom: "japońskie startupy deeptech (energetyka, materiały, IT, robotics, bio)",
    requirements: "spółka japońska, projekt deeptech, wpisanie w priorytet NEDO",
    description: "Największy japoński program grantowy dla deeptech.",
    details: "Program SBIR-J zreformowany w 2024, nowe rundy corocznie.",
    officialUrl: "https://www.nedo.go.jp/english/",
    tags: ["deeptech", "JP", "NEDO"],
  },
  {
    name: "Korea TIPS (Tech Incubator Program for Startups)",
    organizer: "MSS Korea / KISED",
    country: "Korea Południowa",
    countryCode: "KR",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 500 mln KRW (~370 000 USD) R&D + do 100 mln KRW startup",
    currency: "KRW",
    fundingType: "grant bezzwrotny + inwestycja przez operatora TIPS",
    forWhom: "koreańskie startupy tech <7 lat, wybrane przez akredytowanego operatora TIPS",
    requirements: "wybór przez operatora TIPS (VC/akcelerator), spółka KR",
    description: "Flagowy koreański program dla tech-startupów.",
    details: "Rekrutacja przez operatorów TIPS przez cały rok.",
    officialUrl: "https://www.jointips.or.kr/",
    tags: ["deeptech", "KR", "TIPS"],
  },
  {
    name: "NZ Callaghan Innovation – R&D Getting Started Grant",
    organizer: "Callaghan Innovation",
    country: "Nowa Zelandia",
    countryCode: "NZ",
    region: Region.WORLD,
    deadlineStatus: DeadlineStatus.ROLLING,
    amount: "do 5 000 NZD za projekt (wcześniejsze granty do 50k) – uwaga: program ewoluuje",
    currency: "NZD",
    fundingType: "grant / R&D tax credit companion",
    forWhom: "startupy NZ prowadzące pierwsze R&D",
    requirements: "spółka NZ, projekt R&D",
    description: "Wsparcie dla firm rozpoczynających R&D w Nowej Zelandii.",
    details: "Program w reformie – weryfikuj aktualną formę na callaghaninnovation.govt.nz.",
    officialUrl: "https://www.callaghaninnovation.govt.nz/",
    tags: ["R&D", "NZ"],
  },
];

const aggregators = [
  {
    name: "granty.pl",
    url: "https://granty.pl/",
    country: "Polska",
    region: Region.PL,
    description: "Największy polski agregator konkursów grantowych i dotacji.",
  },
  {
    name: "atlasdotacji.pl",
    url: "https://atlasdotacji.pl/",
    country: "Polska",
    region: Region.PL,
    description: "Katalog dotacji dla firm i startupów w PL.",
  },
  {
    name: "dotacjomat.pl",
    url: "https://dotacjomat.pl/",
    country: "Polska",
    region: Region.PL,
    description: "Wyszukiwarka dotacji dla polskich firm.",
  },
  {
    name: "grantbot.pl",
    url: "https://grantbot.pl/",
    country: "Polska",
    region: Region.PL,
    description: "Blog + wyszukiwarka dotacji PARP/NCBR/RPO.",
  },
  {
    name: "funduszeeuropejskie.gov.pl",
    url: "https://www.funduszeeuropejskie.gov.pl/",
    country: "Polska",
    region: Region.PL,
    description: "Oficjalny portal Funduszy Europejskich w PL.",
  },
  {
    name: "parp.gov.pl – harmonogram naborów",
    url: "https://www.parp.gov.pl/harmonogram-naborow",
    country: "Polska",
    region: Region.PL,
    description: "Oficjalny harmonogram naborów PARP.",
  },
  {
    name: "NCBR – harmonogram konkursów",
    url: "https://www.gov.pl/web/ncbr/harmonogram-konkursow-2026",
    country: "Polska",
    region: Region.PL,
    description: "Oficjalny harmonogram konkursów NCBR.",
  },
  {
    name: "EU Funding & Tenders Portal",
    url: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/",
    country: "UE",
    region: Region.EU,
    description:
      "Główny portal konkursów Komisji Europejskiej (Horizon, EIC, Digital Europe, LIFE, itd.).",
  },
  {
    name: "EIC Community",
    url: "https://eic.ec.europa.eu/",
    country: "UE",
    region: Region.EU,
    description: "Oficjalna strona European Innovation Council.",
  },
  {
    name: "Eureka Network",
    url: "https://www.eurekanetwork.org/",
    country: "UE",
    region: Region.EU,
    description: "Międzyrządowa sieć programów Eureka (Eurostars, Clusters, GlobalStars).",
  },
  {
    name: "grants.gov (USA)",
    url: "https://www.grants.gov/",
    country: "USA",
    region: Region.WORLD,
    description: "Federalny portal konkursów grantowych w USA.",
  },
  {
    name: "sbir.gov",
    url: "https://www.sbir.gov/",
    country: "USA",
    region: Region.WORLD,
    description: "Centralny portal SBIR/STTR – 11 agencji federalnych.",
  },
  {
    name: "innovationisrael.org.il",
    url: "https://innovationisrael.org.il/en/",
    country: "Izrael",
    region: Region.WORLD,
    description: "Israel Innovation Authority – wszystkie programy IIA.",
  },
  {
    name: "startupsg.gov.sg",
    url: "https://www.startupsg.gov.sg/",
    country: "Singapur",
    region: Region.WORLD,
    description: "Portal Startup SG – wszystkie programy Enterprise Singapore dla startupów.",
  },
  {
    name: "business.gov.au – grants & programs",
    url: "https://business.gov.au/grants-and-programs",
    country: "Australia",
    region: Region.WORLD,
    description: "Oficjalny agregator programów wsparcia dla biznesu w Australii.",
  },
  {
    name: "gov.uk innovation funding service",
    url: "https://apply-for-innovation-funding.service.gov.uk/competition/search",
    country: "Wielka Brytania",
    region: Region.EU,
    description: "Konkursy Innovate UK / UKRI.",
  },
  {
    name: "Bpifrance",
    url: "https://www.bpifrance.fr/",
    country: "Francja",
    region: Region.EU,
    description: "Bank publiczny Francji – wszystkie programy dla startupów/MŚP.",
  },
  {
    name: "exist.de",
    url: "https://www.exist.de/",
    country: "Niemcy",
    region: Region.EU,
    description: "Oficjalna strona EXIST + niemieckie ekosystemy startupowe.",
  },
];

async function main() {
  await prisma.aggregator.deleteMany();
  await prisma.program.deleteMany();

  for (const p of programs) {
    const coords = COUNTRY_COORDS[p.countryCode];
    if (!coords) throw new Error(`Brak współrzędnych dla ${p.countryCode}`);
    await prisma.program.create({
      data: {
        name: p.name,
        shortName: p.shortName,
        organizer: p.organizer,
        country: p.country,
        countryCode: p.countryCode,
        region: p.region,
        latitude: p.latOverride ?? coords.lat,
        longitude: p.lngOverride ?? coords.lng,
        applyOpen: p.applyOpen ? new Date(p.applyOpen) : null,
        applyDeadline: p.applyDeadline ? new Date(p.applyDeadline) : null,
        deadlineStatus: p.deadlineStatus,
        amount: p.amount,
        currency: p.currency,
        fundingType: p.fundingType,
        forWhom: p.forWhom,
        requirements: p.requirements,
        description: p.description,
        details: p.details,
        officialUrl: p.officialUrl,
        tags: p.tags,
      },
    });
  }

  for (const a of aggregators) {
    await prisma.aggregator.create({ data: a });
  }

  console.log(
    `Seeded ${programs.length} programs and ${aggregators.length} aggregators.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
